criterion:
  type: CrossEntropyLoss
data:
  args:
  - download: true
  consistent_label_distribution: true
  root: data/
  splits:
  - 0.8
  - 0.2
  - 0.2
  splitter: lda
  splitter_args:
  - alpha: 0.2
  subsample: 0.2
  transform:
  - - ToTensor
  - - Normalize
    - mean:
      - 0.4914
      - 0.4822
      - 0.4465
      std:
      - 0.247
      - 0.2435
      - 0.2616
  type: CIFAR10@torchvision
dataloader:
  batch_size: 32
device: 0
early_stop:
  patience: 0
eval:
  best_res_update_round_wise_key: test_acc
  freq: 5
  metrics:
  - acc
  - correct
  - f1
  - classification_report
  - confusion_matrix
federate:
  client_num: 3
  merge_test_data: false
  mode: standalone
  sample_client_num: 3
  sampler: uniform
  save_to: Alpha_tune_ls_epoch_epoch_FedAvg_cifar10_fedex_3_clients_50_20_10_consistent_label.pth
  share_local_model: false
  total_round_num: 205
  use_diff: true
grad:
  grad_clip: 5.0
hpo:
  fedex:
    diff: false
    eta0: -1.0
    gamma: 0.0
    sched: aggressive
    ss: scripts/marketplace/example_scripts/cifar10/avg/fedex_grid_search_space_large_v1.yaml
    use: false
  metric: client_summarized_weighted_avg.val_avg_loss
  working_folder: fedex_epoch_cifar10_avg_alpha_3_clients_50_20_10_consistent_label
marketplace:
  alpha_tune:
    aggregation_weight_candidates:
    - - 0.7
      - 0.1
      - 0.2
    - - 0.3
      - 0.3
      - 0.4
    - - 0.1
      - 0.2
      - 0.7
    - - 0.1
      - 0.7
      - 0.2
    - - 0.5
      - 0.3
      - 0.2
    - - 0.2
      - 0.5
      - 0.3
    - - 0.2
      - 0.3
      - 0.5
    aggregation_weight_sha_metric: f1
    aggregation_weight_sha_round: 5
    aggregation_weight_sha_use: true
    client_bid:
    - 10
    - 20
    - 50
    entropy_determined: false
    info_matrix_pth: info_matrix/3_clients_444_inf_matrix.pickle
    tau_alpha: 1
  alpha_tune_use: true
model:
  hidden: 512
  model_num_per_trainer: 5
  out_channels: 10
  type: convnet2
outdir: exp_v1_order_bug_agg_weight_sha/exp_ls_epoch_alpha_tune_3_client_10:20:50_seed_444_tmp_alpha_1
seed: 444
train:
  batch_or_epoch: epoch
  local_update_steps: 2
  optimizer:
    lr: 0.5
    weight_decay: 0.0
trainer:
  type: cvtrainer
use_gpu: true
